name: Docker Image CI

on:
    push:
        tags:
            - "v*.*.*"
    workflow_dispatch:

jobs:

    build:
        name: Build Docker image
        runs-on: ubuntu-latest

        steps:
            -   name: Docker meta
                id: meta
                uses: docker/metadata-action@v5
                with:
                    images: |
                        ghentcdh/gentgemapt-frontend
                    tags: |
                        type=ref,event=branch
                        type=ref,event=pr
                        type=semver,pattern={{version}}
                        type=semver,pattern={{major}}.{{minor}}
                        type=semver,pattern={{major}}
            -   name: Checkout code
                uses: actions/checkout@v4
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
            -   name: Login to DockerHub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -   name: Build and push
                uses: docker/build-push-action@v6
                with:
                    context: .
                    push: true
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
                    cache-from: type=registry,ref=ghentcdh/gentgemapt_frontend:buildcache
                    cache-to: type=registry,ref=ghentcdh/gentgemapt_frontend:buildcache,mode=max
